<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title id="site_title">Задачи Андрея Литвицкого</title>
    <link rel="stylesheet" type="text/css" href="/css/styles.css">
</head>
<body>
<header class="glass-header">
    <h1>Задачи Андрея Литвицкого</h1>
</header>
<main>
    <div class="tabs-container">
        <!-- Добавьте сколько угодно вкладок -->
        <div id="loader" style="display: none;">Загрузка...</div>
    </div>
    <div class="task-content">
        <p>Здесь объявлены задачи, которые вы можете попробовать решить</p>
    </div>
</main>
</body>
<script src="/scripts/script.js"></script>
</html>