<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Задача</title>
    <link rel="stylesheet" type="text/css" href="/css/styles.css">
</head>
<body>
<header class="glass-header">
    <h1>Задачи Андрея Литвицкого</h1>
</header>
<main>
    <div class="task-content">
        <div id="loader" style="display: none;">Загрузка...</div>
        <div class="task-info">
            <h2></h2>
            <p></p>
        </div>
        <a class="back-button">Назад</a>
    </div>
</main>
</body>
<script src="/scripts/script2.js"></script>
</html>
